enabled: true
description: Pipeline to show how to use cache and record analytics
routes:
  - path: good-books-ds-pipeline/_reactivesearch
    method: POST
    classify:
      category: reactivesearch

envs:
  category: reactivesearch
  index:
    - good-books-ds-pipeline
  urlValues:
    cache: true

stages:
  - use: authorization
  - use: searchRelevancy
    inputs:
      search:
        dataField:
          - original_title
        size: 1
      suggestion:
        dataField:
          - original_title
        enablePopularSuggestions: true
        size: 3
        popularSuggestionsConfig:
          size: 1
        enableRecentSuggestions: true
        recentSuggestionsConfig:
          size: 1
    continueOnError: false
  - use: useCache
  - use: reactivesearchQuery
    continueOnError: false
  - use: elasticsearchQuery
    continueOnError: false
  - use: recordAnalytics
