enabled: true
description: Pipeline to save search to an Elasticsearch index
routes:
  - path: "/saved-search-demo"
    method: POST
    classify:
      category: reactivesearch
envs:
  category: reactivesearch
  index:
    - test
  save_search_URL: ${{ SAVED_SEARCH_URL }}
  save_search_METHOD: "POST"
  save_search_headers: '{"Content-Type": "application/json"}'

stages:
  - use: authorization
  - id: save_search
    async: true
    scriptRef: "saveSearch.js"
  - use: reactivesearchQuery
    needs:
      - save_search
  - use: elasticsearchQuery
