enabled: true
routes:
  - path: "/amazon_reviews/_reactivesearch"
    method: POST
    classify:
      category: reactivesearch

stages:
  - id: authorize user
    use: authorization
  - id: fetch embeddings
    use: openAIEmbeddings
    inputs:
      apiKey: "${{ OPEN_AI_API_KEY }}"
      useWithReactiveSearchQuery: true
    continueOnError: false
  - use: reactivesearchQuery
    needs:
      - fetch embeddings
    continueOnError: false
  - use: elasticsearchQuery
    continueOnError: false
