enabled: true
description: Pipeline to show usage of httpRequest stage
routes:
  - path: books/suggestions
    method: POST
    classify:
      category: reactivesearch

stages:
  - id: data_muse_api
    description: To get data from data muse api in asynchronous manner
    use: httpRequest
    async: true
    inputs:
      url: https://api.datamuse.com/sug
      params:
        s: "{{context.envs.query}}"
    continueOnError: false
  - use: reactivesearchQuery
    continueOnError: false
  - use: elasticsearchQuery
    async: true
    continueOnError: false
  - id: merge_response
    description: Merges the data muse response to RS API response
    needs:
    - data_muse_api
    scriptRef: 'merge.js'
