name: ReactiveSearch Pipeline Deployment

on: [push]

jobs:
  deploy_pipeline:
    runs-on: ubuntu-latest
    name: Deploy the pipeline
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy Pipeline
        uses: appbaseio/pipelines-action@0.1.1
        with:
          url: ${{secrets.APPBASEIOURL}}
          file: "./basic/pipeline.yaml"