name: Generate One-Click pipeline configurations

on: [push]

jobs:
  generate_one_click:
    runs-on: ubuntu-latest
    name: Generate One Click Configs
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use node js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
        working-directory: ./.scripts
      - name: Run one-click generation
        run: sh ./generate-oneclick.sh
        working-directory: ./.scripts
      - name: Add and Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actions
          message: Generate one-click pipeline configurations
          push: true
