name: Generate One-Click pipeline configurations

on: [push]

jobs:
  generate_one_click:
    runs-on: ubuntu-latest
    name: Generate One Click Configs
    strategy:
      matrix:
        plugin: [basic, cache_analytics, http_request, knn_search, knowledge_graph, mongodb, query_rules, saved_search, solr, solr_validate, vector_indexing]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Move to Scripts Directory
        run: cd .scripts
      - name: Use node js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Run ${{matrix.plugin}} one-click generation
        run: yarn one-click ${{ format('../{0}/pipeline.yaml', matrix.plugin) }}
      - name: Add and Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actions
          message: Generate one-click pipeline configurations
          push: true
